/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../lazy.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/http/src/http_module';
import * as import4 from '@angular/http/src/backends/browser_xhr';
import * as import5 from '@angular/http/src/base_response_options';
import * as import6 from '@angular/http/src/backends/xhr_backend';
import * as import7 from '@angular/http/src/base_request_options';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from '@angular/http/src/interfaces';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/router/src/router_config_loader';
import * as import12 from '@angular/core/src/render/api';
import * as import13 from '@angular/core/src/linker/view';
import * as import14 from '@angular/core/src/linker/element';
import * as import15 from '@angular/core/src/linker/view_utils';
import * as import16 from '@angular/core/src/linker/view_type';
import * as import17 from '@angular/core/src/change_detection/change_detection';
import * as import18 from '@angular/core/src/metadata/view';
import * as import19 from '@angular/core/src/linker/component_factory';
class LazyModuleInjector extends import0.NgModuleInjector<import1.LazyModule> {
  _RouterModule_0:import2.RouterModule;
  _HttpModule_1:import3.HttpModule;
  _BrowserXhr_2:import4.BrowserXhr;
  _ResponseOptions_3:import5.BaseResponseOptions;
  _XSRFStrategy_4:any;
  _XHRBackend_5:import6.XHRBackend;
  _RequestOptions_6:import7.BaseRequestOptions;
  _Http_7:any;
  _LazyModule_8:import1.LazyModule;
  __ROUTES_9:any[];
  constructor(parent:import8.Injector) {
    super(parent,[LazyComponentNgFactory],[]);
  }
  get _ROUTES_9():any[] {
      if ((this.__ROUTES_9 == (null as any))) { (this.__ROUTES_9 = [[
        {
          path: '',
          component: import1.LazyComponent,
          pathMatch: 'full'
        }
        ,
        {
          path: 'feature',
          loadChildren: './feature/feature.module#FeatureModule'
        }

      ]
    ]); }
    return this.__ROUTES_9;
  }
  createInternal():import1.LazyModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._HttpModule_1 = new import3.HttpModule();
    this._BrowserXhr_2 = new import4.BrowserXhr();
    this._ResponseOptions_3 = new import5.BaseResponseOptions();
    this._XSRFStrategy_4 = import3._createDefaultCookieXSRFStrategy();
    this._XHRBackend_5 = new import6.XHRBackend(this._BrowserXhr_2,this._ResponseOptions_3,this._XSRFStrategy_4);
    this._RequestOptions_6 = new import7.BaseRequestOptions();
    this._Http_7 = import3.httpFactory(this._XHRBackend_5,this._RequestOptions_6);
    this._LazyModule_8 = new import1.LazyModule(this._Http_7);
    return this._LazyModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.HttpModule)) { return this._HttpModule_1; }
    if ((token === import4.BrowserXhr)) { return this._BrowserXhr_2; }
    if ((token === import5.ResponseOptions)) { return this._ResponseOptions_3; }
    if ((token === import9.XSRFStrategy)) { return this._XSRFStrategy_4; }
    if ((token === import6.XHRBackend)) { return this._XHRBackend_5; }
    if ((token === import7.RequestOptions)) { return this._RequestOptions_6; }
    if ((token === import10.Http)) { return this._Http_7; }
    if ((token === import1.LazyModule)) { return this._LazyModule_8; }
    if ((token === import11.ROUTES)) { return this._ROUTES_9; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const LazyModuleNgFactory:import0.NgModuleFactory<import1.LazyModule> = new import0.NgModuleFactory(LazyModuleInjector,import1.LazyModule);
var renderType_LazyComponent_Host:import12.RenderComponentType = (null as any);
class _View_LazyComponent_Host0 extends import13.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import14.AppElement;
  _LazyComponent_0_4:import1.LazyComponent;
  constructor(viewUtils:import15.ViewUtils,parentInjector:import8.Injector,declarationEl:import14.AppElement) {
    super(_View_LazyComponent_Host0,renderType_LazyComponent_Host,import16.ViewType.HOST,viewUtils,parentInjector,declarationEl,import17.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import14.AppElement {
    this._el_0 = this.selectOrCreateHostElement('lazy-comp',rootSelector,(null as any));
    this._appEl_0 = new import14.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LazyComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LazyComponent_0_4 = new import1.LazyComponent();
    this._appEl_0.initComponent(this._LazyComponent_0_4,[],compView_0);
    compView_0.create(this._LazyComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.LazyComponent) && (0 === requestNodeIndex))) { return this._LazyComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_LazyComponent_Host0(viewUtils:import15.ViewUtils,parentInjector:import8.Injector,declarationEl:import14.AppElement):import13.AppView<any> {
  if ((renderType_LazyComponent_Host === (null as any))) { (renderType_LazyComponent_Host = viewUtils.createRenderComponentType('',0,import18.ViewEncapsulation.None,[],{})); }
  return new _View_LazyComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const LazyComponentNgFactory:import19.ComponentFactory<import1.LazyComponent> = new import19.ComponentFactory<import1.LazyComponent>('lazy-comp',viewFactory_LazyComponent_Host0,import1.LazyComponent);
const styles_LazyComponent:any[] = [];
var renderType_LazyComponent:import12.RenderComponentType = (null as any);
class _View_LazyComponent0 extends import13.AppView<import1.LazyComponent> {
  _text_0:any;
  constructor(viewUtils:import15.ViewUtils,parentInjector:import8.Injector,declarationEl:import14.AppElement) {
    super(_View_LazyComponent0,renderType_LazyComponent,import16.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import17.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import14.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'lazy!',(null as any));
    this.init([],[this._text_0],[],[]);
    return (null as any);
  }
}
export function viewFactory_LazyComponent0(viewUtils:import15.ViewUtils,parentInjector:import8.Injector,declarationEl:import14.AppElement):import13.AppView<import1.LazyComponent> {
  if ((renderType_LazyComponent === (null as any))) { (renderType_LazyComponent = viewUtils.createRenderComponentType('/Users/robertsbt/projects/ngcli-test-app/app/lazy.module.ts class LazyComponent - inline template',0,import18.ViewEncapsulation.None,styles_LazyComponent,{})); }
  return new _View_LazyComponent0(viewUtils,parentInjector,declarationEl);
}