// Code generated by angular2-stress-test

import { Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-root',
  //encapsulation: ViewEncapsulation.None,
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent { }
