/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../feature/feature.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from '@angular/router/src/router_config_loader';
import * as import5 from '@angular/core/src/render/api';
import * as import6 from '@angular/core/src/linker/view';
import * as import7 from '@angular/core/src/linker/element';
import * as import8 from '@angular/core/src/linker/view_utils';
import * as import9 from '@angular/core/src/linker/view_type';
import * as import10 from '@angular/core/src/change_detection/change_detection';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
class FeatureModuleInjector extends import0.NgModuleInjector<import1.FeatureModule> {
  _RouterModule_0:import2.RouterModule;
  _FeatureModule_1:import1.FeatureModule;
  __ROUTES_2:any[];
  constructor(parent:import3.Injector) {
    super(parent,[FeatureComponentNgFactory],[]);
  }
  get _ROUTES_2():any[] {
        if ((this.__ROUTES_2 == (null as any))) { (this.__ROUTES_2 = [[{
          path: '',
          component: import1.FeatureComponent
        }
    ]]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.FeatureModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._FeatureModule_1 = new import1.FeatureModule();
    return this._FeatureModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.FeatureModule)) { return this._FeatureModule_1; }
    if ((token === import4.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const FeatureModuleNgFactory:import0.NgModuleFactory<import1.FeatureModule> = new import0.NgModuleFactory(FeatureModuleInjector,import1.FeatureModule);
var renderType_FeatureComponent_Host:import5.RenderComponentType = (null as any);
class _View_FeatureComponent_Host0 extends import6.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import7.AppElement;
  _FeatureComponent_0_4:import1.FeatureComponent;
  constructor(viewUtils:import8.ViewUtils,parentInjector:import3.Injector,declarationEl:import7.AppElement) {
    super(_View_FeatureComponent_Host0,renderType_FeatureComponent_Host,import9.ViewType.HOST,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.AppElement {
    this._el_0 = this.selectOrCreateHostElement('feature-component',rootSelector,(null as any));
    this._appEl_0 = new import7.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FeatureComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FeatureComponent_0_4 = new import1.FeatureComponent();
    this._appEl_0.initComponent(this._FeatureComponent_0_4,[],compView_0);
    compView_0.create(this._FeatureComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.FeatureComponent) && (0 === requestNodeIndex))) { return this._FeatureComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_FeatureComponent_Host0(viewUtils:import8.ViewUtils,parentInjector:import3.Injector,declarationEl:import7.AppElement):import6.AppView<any> {
  if ((renderType_FeatureComponent_Host === (null as any))) { (renderType_FeatureComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_FeatureComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const FeatureComponentNgFactory:import12.ComponentFactory<import1.FeatureComponent> = new import12.ComponentFactory<import1.FeatureComponent>('feature-component',viewFactory_FeatureComponent_Host0,import1.FeatureComponent);
const styles_FeatureComponent:any[] = [];
var renderType_FeatureComponent:import5.RenderComponentType = (null as any);
class _View_FeatureComponent0 extends import6.AppView<import1.FeatureComponent> {
  _text_0:any;
  constructor(viewUtils:import8.ViewUtils,parentInjector:import3.Injector,declarationEl:import7.AppElement) {
    super(_View_FeatureComponent0,renderType_FeatureComponent,import9.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'foo.html',(null as any));
    this.init([],[this._text_0],[],[]);
    return (null as any);
  }
}
export function viewFactory_FeatureComponent0(viewUtils:import8.ViewUtils,parentInjector:import3.Injector,declarationEl:import7.AppElement):import6.AppView<import1.FeatureComponent> {
  if ((renderType_FeatureComponent === (null as any))) { (renderType_FeatureComponent = viewUtils.createRenderComponentType('/Users/robertsbt/projects/ngcli-test-app/app/feature/feature.module.ts class FeatureComponent - inline template',0,import11.ViewEncapsulation.None,styles_FeatureComponent,{})); }
  return new _View_FeatureComponent0(viewUtils,parentInjector,declarationEl);
}